name: バックログアイテム
description: スプリントレビューをするタスクのフォーマット
title: "〜は、〜のため、〜する"
body:
  - type: markdown
    attributes:
      value: |
        ## ユースケース記述

  - type: input
    attributes:
        label: "Link"

  - type: markdown
    attributes:
      value: |
        ## CRUD 図
        [Google Drive](https://docs.google.com/spreadsheets/d/17O3IFrGYoeAbU_15SaLBwGCD1vudgWyBRk_e0rkpoPQ/edit#gid=0)

        ## エンドポイント

  - type: input
    attributes:
        label: "URL"
  - type: textarea
    attributes:
        label: "Request"
  - type: textarea
    attributes:
        label: "Response"

  - type: markdown
    attributes:
      value: |
        ## 特記事項

  - type: textarea
    attributes:
        label: "Note"

